set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab
syntax on
let g:powerline_pycmd = 'py3'
:set laststatus=2 "To show the statusline all the time (not only with multiple windows)
:set number
