# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '$HOME/.zshrc'

#autoload -Uz compinit
#compinit
# End of lines added by compinstall


# Oh my ZSH stuff
export ZSH=$HOME/.oh-my-zsh

plugins=( 
    git
    bundler
    dotenv
    osx
    rake
    rbenv
    ruby
)
#ZSH_THEME="agnoster"

source $ZSH/oh-my-zsh.sh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
powerline-daemon -q
. /usr/lib/python3.8/site-packages/powerline/bindings/zsh/powerline.zsh

# Aliases
alias ls=exa
alias em="emacsclient -ct"
alias nh="st -f \"Dejavu Sans Mono:pixelsize=20\" -e zsh -c 'echo \"Make this window full screen and press ENTER\"; read; stty columns 80; stty rows 24; asciinema rec -c \"ssh nethack@alt.org\" --title \"Nethack gameplay - $(date)\"'"
alias weather="curl wttr.in/Milan"
alias rr="curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash"
alias pip-upgrade="pip list --user --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U"
alias clean-downloads='sh ~/bin/clean-downloads.sh'

export PATH=$PATH:/opt/yices-1.0.40/bin/
export PATH=$PATH:~/.local/bin/ #pip executables
export TERM=xterm-256color
#export LANG=en_US.UTF-8
export LC_ALL="en_US.UTF8"  # fix for vim whitespaces and tabs
#export LC_CTYPE="en_US.UTF-8"
export ANTLR4_JAR=/opt/antlr4/antlr-4.7.2-complete.jar
export visual="vim"


autoload -U promptinit; promptinit
prompt spaceship
SPACESHIP_TIME_SHOW=true
SPACESHIP_USER_SHOW=always
SPACESHIP_HOST_SHOW=always

fpath=($fpath "/home/andrea/.zfunctions")
eval $(thefuck --alias)
