* Dotfiles

This repository contains the configuration of my personal computer,
while I tried to keep it general and not too specific, this is undoubtedly
thought for me. I keep my personal information as username or email in a 
sperated file but this doesn't means that you can simply clone this repository,
change the personal information and hope that all works perfectly.

In this repository there are two folders:

- ~nixos/~ includes several ~.nix~ sources that describes my system configuration
- ~dotfiles/~ has different subfolders for every program that needs a specific configuration

I frequently change my environment but I'm qute satisfied with my last approach:
NixOS with EXWM (Xorg) trying to use as little as possible tools not interfaced
somehow to Emacs. ~qutebrowser` is an example of external program I use.

** Usage
I usually just clone this repository into my home, I generate the ~hardware-configuration.nix~
in ~/etc/nixos/~ with ~nixos-rebuild~ and then I symlink ~/etc/nixos/configuration.nix~ to
the ~configuration.nix~ in my repository:

#+begin_src shell
ln -s ~/dotfiles/configuration.nix /etc/nixos/configuration.nix
#+end_src


** NixOS
   + ~user.nix~ defines some personal information
   + ~configuration.nix~ is the main system configuration, it contains things like
     + user information (home directory, groups, shell, etc...)
     + enabled services and their configuration
     + network configuration
     + time zone settings
     + kernel modules
     + overlays
       + [[https://github.com/nix-community/emacs-overlay][emacs-overlay]]
       + custom overlay with custom packages
     + fonts
     + other various things
   + ~home.nix~ is the [[https://github.com/rycee/home-manager][home-manager]] configuration, it contains things like
     + programs I use
     + zsh configuration, it inclued things like
       + [[https://github.com/ohmyzsh/ohmyzsh][oh-my-zsh]]
       + [[https://github.com/denysdovhan/spaceship-prompt][spaceship-prompt]]
     + git configuration
     + gpg agent configuration
   + ~sources.nix~ contains the list of my sources, included the local ~custom-overlay~
     which exports the packages in ~custom-pkgs/~
   
   

** Dotfiles
*** Emacs
    My Emacs configuration is a work in progress that I constantly update when I learn
    new packages. Since I'm using ~emacs-overlay~ I chosed to keep everything inside a
    single file, i.e. ~init.el~. Indeed the overlay automatically downloads and installs
    the packages as NixOS derivations.

    This section of the ~README~ would require a lot of documentation, maybe on day...

*** Qutebrowser
    All the settings are inside the ~config.py~ file, there is not much to say.

*** Xorg
    I only have a ~.xinitrc~ that starts Emacs.

*** Zsh
    The real ~zsh~ configuration is generated by ~home-configuration~ and it's declaratively
    described in ~home.nix~. However I needed ~.zlogin~ to automatically start Xorg when
    I log on tty1.
