directory: ~/nas/musica/
library: ~/nas/musica/library.blb
import:
    copy: yes
    write: yes
    resume: ask
    log: ~/nas/musica/beets.log
ui:
    color: yes
plugins: fetchart convert
convert:
    auto: yes