directory: ~/nas/musica/
library: ~/nas/musica/library.blb
import:
    copy: yes
    write: yes
    resume: ask
    log: ~/nas/musica/beet.log
ui:
    color: yes
plugins: fetchart embedart convert edit
convert:
    auto: yes